CREATE TABLE IF NOT EXISTS `alerts` (
  `ID` varchar(64) NOT NULL,
  `STATUS` enum('ALERT','WARNING') NOT NULL,
  `PARAMETER` varchar(100) NOT NULL,
  `VALUE` double NOT NULL,
  `THRESHOLD` double NOT NULL,
  `TIMESTAMP` datetime NOT NULL,
  `MACHINE` varchar(100) NOT NULL,
  `STATE` enum('NOT ASSIGNED','ASSIGNED') NOT NULL DEFAULT 'NOT ASSIGNED',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_ALERTS_MACHINE` (`MACHINE`),
  KEY `IDX_ALERTS_STATUS` (`STATUS`),
  KEY `IDX_ALERTS_STATE` (`STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
