CREATE TABLE IF NOT EXISTS `pdca_cases` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ALERT_ID` varchar(64) DEFAULT NULL,
  `TITLE` varchar(255) NOT NULL,
  `DESCRIPTION` text,
  `OWNER_USER_ID` int NOT NULL,
  `CREATED_BY_USER_ID` int NOT NULL,
  `PHASE` enum('PLAN','DO','CHECK','ACT','CLOSED') NOT NULL DEFAULT 'PLAN',
  `STATUS` enum('ACTIVE','CANCELLED','COMPLETED') NOT NULL DEFAULT 'ACTIVE',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PDCA_CASES_ALERT_ID` (`ALERT_ID`),
  KEY `IDX_PDCA_CASES_OWNER` (`OWNER_USER_ID`),
  KEY `FK_PDCA_CASES_CREATED_BY` (`CREATED_BY_USER_ID`),
  CONSTRAINT `FK_PDCA_CASES_CREATED_BY` FOREIGN KEY (`CREATED_BY_USER_ID`) REFERENCES `users` (`ID`),
  CONSTRAINT `FK_PDCA_CASES_OWNER` FOREIGN KEY (`OWNER_USER_ID`) REFERENCES `users` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
