CREATE TABLE IF NOT EXISTS `pdca_tasks` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PDCA_CASE_ID` int NOT NULL,
  `TITLE` varchar(255) NOT NULL,
  `DESCRIPTION` text,
  `TEAM` varchar(50) NOT NULL,
  `WEIGHT_PERCENT` int NOT NULL,
  `PHASE` enum('PLAN','DO','CHECK','ACT') NOT NULL DEFAULT 'PLAN',
  `STATUS` enum('NOT_STARTED','IN_PROGRESS','DONE','REJECTED') NOT NULL DEFAULT 'NOT_STARTED',
  `PROGRESS_PERCENT` int NOT NULL DEFAULT 0,
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_PDCA_TASKS_CASE` (`PDCA_CASE_ID`),
  KEY `IDX_PDCA_TASKS_TEAM` (`TEAM`),
  KEY `IDX_PDCA_TASKS_CASE_PHASE` (`PDCA_CASE_ID`,`PHASE`),
  CONSTRAINT `FK_PDCA_TASKS_CASE` FOREIGN KEY (`PDCA_CASE_ID`) REFERENCES `pdca_cases` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
