CREATE TABLE IF NOT EXISTS `teams` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CODE` varchar(50) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `MANAGER_USER_ID` int DEFAULT NULL,
  `FOREMAN_USER_ID` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_TEAMS_CODE` (`CODE`),
  KEY `IDX_TEAMS_MANAGER` (`MANAGER_USER_ID`),
  KEY `IDX_TEAMS_FOREMAN` (`FOREMAN_USER_ID`),
  CONSTRAINT `FK_TEAMS_MANAGER_USER` FOREIGN KEY (`MANAGER_USER_ID`) REFERENCES `users` (`ID`),
  CONSTRAINT `FK_TEAMS_FOREMAN_USER` FOREIGN KEY (`FOREMAN_USER_ID`) REFERENCES `users` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
