CREATE TABLE IF NOT EXISTS `people` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_CODE` varchar(50) NOT NULL,
  `FIRSTNAME` varchar(100) NOT NULL,
  `LASTNAME` varchar(100) NOT NULL,
  `TEAM_ID` int NOT NULL,
  `IS_FOREMAN` tinyint(1) NOT NULL DEFAULT 0,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_PEOPLE_EMPLOYEE_CODE` (`EMPLOYEE_CODE`),
  KEY `IDX_PEOPLE_TEAM` (`TEAM_ID`),
  CONSTRAINT `FK_PEOPLE_TEAM` FOREIGN KEY (`TEAM_ID`) REFERENCES `teams` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
