CREATE TABLE IF NOT EXISTS `pdca_task_people_assignees` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TASK_ID` int NOT NULL,
  `PERSON_ID` int NOT NULL,
  `ROLE_IN_TASK` enum('OWNER','EXECUTOR','OBSERVER') NOT NULL DEFAULT 'EXECUTOR',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_TASK_PERSON_ROLE` (`TASK_ID`,`PERSON_ID`,`ROLE_IN_TASK`),
  KEY `IDX_TASK_PEOPLE_TASK` (`TASK_ID`),
  KEY `IDX_TASK_PEOPLE_PERSON` (`PERSON_ID`),
  CONSTRAINT `FK_TASK_PEOPLE_TASK` FOREIGN KEY (`TASK_ID`) REFERENCES `pdca_tasks` (`ID`),
  CONSTRAINT `FK_TASK_PEOPLE_PERSON` FOREIGN KEY (`PERSON_ID`) REFERENCES `people` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
