CREATE TABLE IF NOT EXISTS `pdca_case_events` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PDCA_CASE_ID` int NOT NULL,
  `EVENT_TYPE` varchar(50) NOT NULL,
  `MESSAGE` text,
  `PAYLOAD_JSON` json,
  `CREATED_BY_USER_ID` int NOT NULL,
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_CASE_EVENTS_CASE_DATE` (`PDCA_CASE_ID`,`CREATE_DATE`),
  KEY `IDX_CASE_EVENTS_TYPE` (`EVENT_TYPE`),
  CONSTRAINT `FK_CASE_EVENTS_CASE` FOREIGN KEY (`PDCA_CASE_ID`) REFERENCES `pdca_cases` (`ID`),
  CONSTRAINT `FK_CASE_EVENTS_CREATED_BY` FOREIGN KEY (`CREATED_BY_USER_ID`) REFERENCES `users` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
