CREATE TABLE IF NOT EXISTS `pdca_case_phases` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PDCA_CASE_ID` int NOT NULL,
  `PHASE` enum('PLAN','DO','CHECK','ACT') NOT NULL,
  `STARTED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `STARTED_BY_USER_ID` int NOT NULL,
  `CLOSED_AT` datetime DEFAULT NULL,
  `CLOSED_BY_USER_ID` int DEFAULT NULL,
  `CLOSE_COMMENT` text,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_CASE_PHASE` (`PDCA_CASE_ID`,`PHASE`),
  KEY `IDX_CASE_PHASE_CASE` (`PDCA_CASE_ID`),
  KEY `IDX_CASE_PHASE_LOOKUP` (`PDCA_CASE_ID`,`PHASE`,`CLOSED_AT`),
  CONSTRAINT `FK_CASE_PHASE_CASE` FOREIGN KEY (`PDCA_CASE_ID`) REFERENCES `pdca_cases` (`ID`),
  CONSTRAINT `FK_CASE_PHASE_STARTED_BY` FOREIGN KEY (`STARTED_BY_USER_ID`) REFERENCES `users` (`ID`),
  CONSTRAINT `FK_CASE_PHASE_CLOSED_BY` FOREIGN KEY (`CLOSED_BY_USER_ID`) REFERENCES `users` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
